openapi: 3.0.1
info:
  title: AviApp
  version: "1.0"
servers:
  - url: https://localhost:7207
    description: Local server
paths:
  /api/login:
    post:
      tags:
        - Auth
      operationId: Login
      summary: Login
      description: Login to the application
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequestDto"
      responses:
        "200":
          description: Jwt token is returned
          content:
            text/plain:
              schema:
                type: string
  
  /api/customers:
    get:
      tags:
        - Customer
      operationId: GetCustomers
      summary: Get all customers
      description: Get all customers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerDto'
                

    post:
      tags:
        - Customer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerDto"
      responses:
        "200":
          description: OK
  /api/customers/{id}:
    get:
      tags:
        - Customer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
    put:
      tags:
        - Customer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerDto"
      responses:
        "200":
          description: OK
    delete:
      tags:
        - Customer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
  /api/menuitems:
    get:
      tags:
        - MenuItem
      responses:
        "200":
          description: OK
    post:
      tags:
        - MenuItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MenuItemDto"
      responses:
        "200":
          description: OK
  /api/menuitems/{id}:
    get:
      tags:
        - MenuItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
    put:
      tags:
        - MenuItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MenuItemDto"
      responses:
        "200":
          description: OK
    delete:
      tags:
        - MenuItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
  /api/orders:
    get:
      tags:
        - Order
      responses:
        "200":
          description: OK
    post:
      tags:
        - Order
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderDto"
      responses:
        "200":
          description: OK
  /api/orders/{id}:
    get:
      tags:
        - Order
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
    put:
      tags:
        - Order
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderDto"
      responses:
        "200":
          description: OK
    delete:
      tags:
        - Order
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          
components:
  schemas:
    CustomerDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
          nullable: true
        customerName:
          type: string
          nullable: true
        phone:
          type: string
          nullable: true
      additionalProperties: false
    LoginRequestDto:
      type: object
      properties:
        email:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
      additionalProperties: false
    MenuItemDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
          nullable: true
        name:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        price:
          type: number
          format: double
        isAvailable:
          type: boolean
      additionalProperties: false
    OrderDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
          nullable: true
        orderDate:
          type: string
          format: date-time
        customerId:
          type: integer
          format: int32
        orderMenuItems:
          type: array
          items:
            $ref: "#/components/schemas/OrderMenuItemDto"
          nullable: true
      additionalProperties: false
    OrderMenuItemDto:
      type: object
      properties:
        orderId:
          type: integer
          format: int32
        menuItemId:
          type: integer
          format: int32
      additionalProperties: false
security:
  - Bearer: []
